language: rust
git:
  depth: 3
rust:
  - stable
  - beta
  - nightly
dist: bionic
before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
  - sudo apt-get -q update
  - sudo apt-get -y install llvm-10
  - sudo apt-get -y install clang-10
before_script:
  - export LLVM_CONFIG_PATH=/usr/bin/llvm-config-10
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
